import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
        // style={{ backgroundImage: `url(${pageAssets.background.src})` }}
      >
        <NavBar />

        <main
          className="
          lg:mt-16 md:mt-14 mt-5
          lg:mb-16 md:mb-14 mb-5
          lg:mx-auto
          max-w-[80rem] mx-5 h-screen "
        >
          {children}
        </main>
      </body>
    </html>
  );
}
